### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by habi** [theveloped/WhatsBook#2]
Whe I try to run the script on one of my exports, I get the error

    ValueError: not enough values to unpack (expected 3, got 1)

The full Traceback is

    [habi@anomalocaris|WhatsBook]:python whatsBook.py folder/ > content.tex 
    Traceback (most recent call last):
      File "whatsBook.py", line 385, in <module>
        main()
      File "whatsBook.py", line 78, in main
        for line in parsedChat:
      File "whatsBook.py", line 238, in parseChat
        parsedDate, month = parseDate(date)
      File "whatsBook.py", line 372, in parseDate
        day, month, year = re.split("[-/]", dateString, 2)
    ValueError: not enough values to unpack (expected 3, got 1)

**Comment by habi** [comment]
A redacted output of `head folder/_chat.txt`looks like this:

```
06.08.13, 19:55:10: ‎You changed the subject to “XXXX”
06.08.13, 19:55:10: ‎You were added
06.08.13, 19:55:10: XXXX was added
06.08.13, 19:55:10: XXXX was added
06.08.13, 19:55:10: ‎XXXX was added
06.08.13, 19:55:38: Habi: 2013-08-06-PHOTO-00000006.jpg <‎attached>
06.08.13, 19:57:24: Habi: XXXX Some text with ä, ö, üs XXXX
09.08.13, 12:50:55: Habi: 2013-08-09-PHOTO-00000008.jpg <‎attached>
09.08.13, 12:53:24: Habi: Das Güpfi links XXXX
09.08.13, 23:20:39: XXXX: Wow! Bellissima!!!
```

**Comment by theveloped** [comment]
Hi David,

Thank you for cathcing the typo. It seems the problem lies with parsing the
date. Most likely this is due to the date delimiter in your export file.
Can you check what delimiter is used in the date formatiing of your export
(this varies between whatsapp versions)? If it is different from either "-"
or "/" the problem would most likely be solved by adding to the regex
pattern on line 372. Hope this solves your problem.

Kind regards,

Tobias

**Comment by theveloped** [comment]
Should be fixed now. Let me know if the problem persists.

**Comment by habi** [comment]
Unfortunately I still get a Traceback.
Now it is
````
anomalocaris:WhatsBook habi$ python whatsBook.py habathuers/ > content.tex
Traceback (most recent call last):
  File "whatsBook.py", line 385, in <module>
    main()
  File "whatsBook.py", line 78, in main
    for line in parsedChat:
  File "whatsBook.py", line 238, in parseChat
    parsedDate, month = parseDate(date)
  File "whatsBook.py", line 373, in parseDate
    date = datetime.date(int("20" + year), int(month), int(day))
ValueError: invalid literal for int() with base 10: '2013,'
````

**Comment by habi** [comment]
It seems that the line.split() in [line 132](https://github.com/theveloped/WhatsBook/blob/master/whatsBook.py#L132) 'adds' a spurious comma at the end.
If I remove it with `date = date[:-1]`, then everything works as expected.

I will *not* submit a pull request, since it might break other peoples export....

**Comment by theveloped** [comment]
Indeed I now see that your `_chat.txt` is indeed differently formatted. Have you by any chance come across even more different export formats? If so please share them here and I can have a look into getting them all supported.

**Comment by habi** [comment]
Here's another (redacted) _chat.txt

```
06.02.15, 10:36:10: ‎XXX created group “XXX”
06.02.15, 10:36:10: ‎XXX added you
06.02.15, 10:36:11: ‎XXX changed this group's icon
06.02.15, 10:36:18: XXX: 😳
16.02.15, 21:11:12: XXX: Ihr zwei Dökter!
16.02.15, 21:11:53: XXX: Ihr könnt auch...
```
